# Generated by Django 3.0.6 on 2020-05-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=50)),
                ('main_food', models.CharField(choices=[('3 Piece', '3 Piece'), ('Box Combo', 'Box Combo'), ('Caniac Combo', 'Caniac Combo')], default="Cane's order", max_length=20)),
            ],
        ),
    ]
