# Generated by Django 3.0.6 on 2020-05-29 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canes', '0004_auto_20200528_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='optional_items',
        ),
    ]
