# Generated by Django 3.0.6 on 2020-05-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canes', '0005_remove_order_optional_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionalItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='additional_items',
            field=models.ManyToManyField(to='canes.OptionalItems'),
        ),
    ]
