# Generated by Django 3.0.6 on 2020-09-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canes', '0006_auto_20200530_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_notes',
            field=models.TextField(default='More notes'),
        ),
    ]
