# Generated by Django 3.0.6 on 2020-05-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='drink',
            field=models.CharField(choices=[('Sweet Tea', 'Sweet Tea'), ('Unsweet Tea', 'Unsweet Tea'), ('Coke', 'Coke'), ('Dr. Pepper', 'Dr. Pepper')], default='Drink Choice', max_length=15),
        ),
    ]
