# Generated by Django 3.0.6 on 2020-05-28 06:01

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('canes', '0003_order_optional_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='optional_items',
        ),
        migrations.AddField(
            model_name='order',
            name='optional_items',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('No slaw', 'No slaw'), ('Extra Toast', 'Extra Toast'), ('Extra Fries', 'Extra Fries'), ('Extra Sauce', 'Extra Sauce')], default='Optional Choices', max_length=43),
        ),
    ]
